### ISSUE TITLE
Hires.fix tab not showing up

### ISSUE THREAD

**Issue by dauwpe** [Amadeus-AI/img2img-hires-fix#4]
Hello,

I installed the addon via automatic1111s extensions tab. After reloading and restarting the UI, it still doesnt show up (it is checked in extensions tab)

**Comment by light-and-ray** [comment]
But there is no tab. Find an accordion in img2img tab

**Comment by cattotaco** [comment]
he is kinda right, he probably got this error, making the accordion dissapear. D:\Oblock\stable-diffusion-webui-1.5.2\stable-diffusion-webui-1.5.2\venv\lib\site-packages\gradio_client\documentation.py:103: UserWarning: Could not get documentation group for <class 'gradio.mix.Series'>: No known documentation group for module 'gradio.mix'
  warnings.warn(f"Could not get documentation group for {cls}: {exc}")
*** Error loading script: img2img_hires_fix.py
    Traceback (most recent call last):
      File "D:\Oblock\stable-diffusion-webui-1.5.2\stable-diffusion-webui-1.5.2\modules\scripts.py", line 319, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "D:\Oblock\stable-diffusion-webui-1.5.2\stable-diffusion-webui-1.5.2\modules\script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "D:\Oblock\stable-diffusion-webui-1.5.2\stable-diffusion-webui-1.5.2\extensions\img2img-hires-fix\scripts\img2img_hires_fix.py", line 8, in <module>
        from modules import scripts, shared, processing, sd_samplers, rng, images, devices, prompt_parser, sd_models, extra_networks, ui_components, sd_schedulers, script_callbacks, extra_networks
    ImportError: cannot import name 'rng' from 'modules' (unknown location)

**Comment by light-and-ray** [comment]
Webui 1.5.2 was outdated about 1.5 years ago o///o
